server:
  port: 9000

spring:
  application:
    name: service-product
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false #禁用nacos配置
    sentinel:
      transport:
        dashboard: localhost:8888
      eager: true